#!/usr/bin/env bash
#
# link-praxstack-skills.sh
#
# Flatten `.claude/skills/praxstack/<skill>/SKILL.md` into Cursor's one-level
# index at `.cursor/skills/<name>/` and `~/.cursor/skills/<name>/`.
#
# Does not rewrite the shared all-pack linker. If a short name is already a
# symlink to another pack, install as `prax-<name>` and log the collision.
# Never deletes a user-owned (non-symlink) Cursor skill directory.
#
# Called from scripts/install-agent-skills.sh and .cursor/environment.json.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HOME_DIR="${HOME:-/home/ubuntu}"
PACK="$REPO_ROOT/.claude/skills/praxstack"
PROJECT_DEST="$REPO_ROOT/.cursor/skills"
HOME_DEST="$HOME_DIR/.cursor/skills"
COLLISION_LOG="$REPO_ROOT/docs/praxstack-skill-collisions.md"

skill_frontmatter_name() {
  local skill_md="$1"
  local name
  name="$(grep -m1 '^name:' "$skill_md" 2>/dev/null | sed 's/^name:[[:space:]]*//; s/^["'\'']//; s/["'\'']$//' | tr -d '[:space:]')"
  printf '%s' "$name"
}

valid_skill_slug() {
  case "$1" in
    *[!A-Za-z0-9._-]*|'') return 1 ;;
    *) return 0 ;;
  esac
}

link_abs_or_skip() {
  local src="$1" dest="$2"
  if [ -e "$dest" ] && [ ! -L "$dest" ]; then
    echo "link-praxstack-skills: left in place (not a symlink): $dest"
    return 1
  fi
  ln -sfn "$src" "$dest"
  return 0
}

relpath_from_cursor_skills() {
  local skill_dir="$1"
  python3 - "$PROJECT_DEST" "$skill_dir" <<'PY'
import os, sys
print(os.path.relpath(sys.argv[2], sys.argv[1]))
PY
}

if [ ! -d "$PACK" ]; then
  echo "link-praxstack-skills: $PACK not present, skipping"
  exit 0
fi

mkdir -p "$PROJECT_DEST" "$HOME_DEST"

# Drop only our previous praxstack-managed links.
for dest in "$PROJECT_DEST" "$HOME_DEST"; do
  [ -d "$dest" ] || continue
  for entry in "$dest"/*; do
    [ -L "$entry" ] || continue
    target="$(readlink "$entry")"
    case "$target" in
      *skills/praxstack/*|*skills/praxstack)
        rm -f "$entry"
        ;;
    esac
  done
done

linked=0
skipped=0
collisions=()

while IFS= read -r -d '' skill_md; do
  skill_dir="$(dirname "$skill_md")"
  dest_name="$(skill_frontmatter_name "$skill_md")"
  [ -n "$dest_name" ] || dest_name="$(basename "$skill_dir")"
  if ! valid_skill_slug "$dest_name"; then
    skipped=$((skipped + 1))
    continue
  fi

  project_hit="$PROJECT_DEST/$dest_name"
  if [ -e "$project_hit" ] || [ -L "$project_hit" ]; then
    if [ -L "$project_hit" ]; then
      existing="$(readlink "$project_hit")"
      case "$existing" in
        *skills/praxstack/*|*skills/praxstack) ;;
        *)
          collisions+=("$dest_name	$existing	prax-$dest_name")
          dest_name="prax-$dest_name"
          if ! valid_skill_slug "$dest_name"; then
            skipped=$((skipped + 1))
            continue
          fi
          ;;
      esac
    elif [ ! -L "$project_hit" ]; then
      collisions+=("$dest_name	(non-symlink)	prax-$dest_name")
      dest_name="prax-$dest_name"
    fi
  fi

  rel="$(relpath_from_cursor_skills "$skill_dir")"
  if ! link_abs_or_skip "$rel" "$PROJECT_DEST/$dest_name"; then
    skipped=$((skipped + 1))
    continue
  fi
  link_abs_or_skip "$skill_dir" "$HOME_DEST/$dest_name" || true
  echo "link-praxstack-skills: $dest_name -> $skill_dir"
  linked=$((linked + 1))
done < <(find "$PACK" -name SKILL.md \
  -type f \
  -not -path '*/.git/*' \
  -not -path '*/node_modules/*' \
  -not -path '*/test/*' \
  -not -path '*/tests/*' \
  -not -path '*/fixtures/*' \
  -not -path '*/references/*' \
  -not -path '*/reference/*' \
  -not -path '*/scripts/*' \
  -not -path '*/workflows/*' \
  -not -path '*/personas/*' \
  -not -path '*/agents/*' \
  -print0)

{
  echo "# Praxstack Cursor skill name collisions"
  echo
  echo "Generated by \`scripts/link-praxstack-skills.sh\`. Cursor indexes one-level"
  echo "directories under \`.cursor/skills/<name>/SKILL.md\`. When a Prax skill"
  echo "name is already taken, it is installed as \`prax-<name>\`."
  echo
  if [ "${#collisions[@]}" -eq 0 ]; then
    echo "No collisions on this run."
    echo
  else
    echo "| Short name | Occupied by | Prefixed install |"
    echo "| --- | --- | --- |"
    for row in "${collisions[@]}"; do
      IFS='	' read -r short occ prefixed <<< "$row"
      echo "| \`$short\` | \`$occ\` | \`$prefixed\` |"
    done
    echo
  fi
} > "$COLLISION_LOG"

echo "link-praxstack-skills: flattened $linked skills (skipped $skipped); wrote $COLLISION_LOG"
